language: java
jdk:
  - oraclejdk8

install:
  - echo "Override default Travis install step to avoid unnecessary './gradlew assemble'."

before_install:
- "export ORG_GRADLE_PROJECT_ideaVersion=${IDEA_VERSION}"
- "export ORG_GRADLE_PROJECT_phpPluginVersion=${PHP_PLUGIN_VERSION}"

#env:
#  - IDEA_VERSION="IU-182.3684.2" PHP_PLUGIN_VERSION="182.3684.40"

script:
  - ./gradlew check buildPlugin -PdownloadIdeaSources=false

before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/

cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
  timeout: 3600